name: fuel-cycle-paper
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - scipy
  - festim
  - pathsim
  - pip
  - pip:
    - git+https://github.com/festim-dev/PathView@glc
    - morethemes